[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "wlzbi"
version = "1.1.0"
description = "Simple colorful terminal logo and typing animation generator"
readme = "README.md"
requires-python = ">=3.9"
license = {text = "MIT"}

authors = [
    {name = "Alen"}
]

dependencies = [
    "cfonts",
    "colorama"
]

[project.urls]
Homepage = "https://pypi.org/project/wlzbi/"
Telegram = "https://t.me/rejerks"
Channel = "https://t.me/wlzbi"
Developer = "Alen — Kerala"

[tool.setuptools.packages.find]
include = ["wlzbi*"]
